stages:
  - test
  - deploy

test:
  image: python:latest
  stage: test
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    USERS_CODE_DIRECTORY: "./files"
  cache:
    paths:
      - .cache/pip
      - venv/
  before_script:
    - python -V
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
  script:
    - py.test -c pytest.ini src/test.py
    - echo "tests done!"
    
deploy:
    stage: deploy
    image: docker:19.03.1
    only:
      - master
    services:
      - docker:19.03.1-dind
    before_script:
      - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD  $CI_REGISTRY
    script:
      - docker build -t $CI_REGISTRY/kireevmp/coderoyale-backend:latest .
      - docker push $CI_REGISTRY/kireevmp/coderoyale-backend:latest
